[package]
name = "arepita-cooker"
version = "0.1.0"
edition = "2026"

[dependencies]
media_codecs = { package = "media-codecs", path = "../../vendor/media-codecs", version = "^0.1" }

[profile.debug]
optimization = 0

[profile.release]
optimization = 3
